load python/3.7.2  : OK 
load ct_tools/2.18  : OK 
unload python/3.7.2  : OK 
load python/3.7.2  : OK 
unload ct_tools/2.18  : OK 
load ct_tools/2.18  : OK 
/work/ALT/odatis/seaice/users/laforga/projet_cryo2ice/code/common_functions.py:257: RuntimeWarning: invalid value encountered in arccos
  dist = earthradius_fct_of_lat(latDeg1)*np.arccos( np.sin(deg_to_rad(latDeg1))*np.sin(deg_to_rad(latDeg2)) + np.cos(deg_to_rad(latDeg1))*np.cos(deg_to_rad(latDeg2))*np.cos(deg_to_rad(lonDeg2 - lonDeg1)) )
sortnsave_cryo2ice_xings.py:148: RuntimeWarning: invalid value encountered in double_scalars
  std = np.ma.sqrt(np.ma.sum(weight1*weight2*(val-mean)**2) / np.ma.sum(weight1*weight2) )
sortnsave_cryo2ice_xings.py:1781: UserWarning: Warning: converting a masked element to nan.
  array = ma.masked_invalid(np.array(is2_data[gdr][p]))
Traceback (most recent call last):
  File "sortnsave_cryo2ice_xings.py", line 2171, in <module>
    data_dict[sat]['xings'] = find_xings2_sat(sat,date_list,file_dict_all[sat],common_data_list)
  File "sortnsave_cryo2ice_xings.py", line 931, in find_xings2_sat
    mean_p = np.ma.mean(param[idx_sub])
TypeError: 'NoneType' object is not subscriptable
