load python/3.7.2  : OK 
load ct_tools/2.18  : OK 
unload python/3.7.2  : OK 
load python/3.7.2  : OK 
unload ct_tools/2.18  : OK 
load ct_tools/2.18  : OK 
/work/ALT/odatis/seaice/users/laforga/projet_cryo2ice/code/common_functions.py:257: RuntimeWarning: invalid value encountered in arccos
  dist = earthradius_fct_of_lat(latDeg1)*np.arccos( np.sin(deg_to_rad(latDeg1))*np.sin(deg_to_rad(latDeg2)) + np.cos(deg_to_rad(latDeg1))*np.cos(deg_to_rad(latDeg2))*np.cos(deg_to_rad(lonDeg2 - lonDeg1)) )
/work/ALT/odatis/seaice/users/laforga/projet_cryo2ice/code/sortnsave_cryo2ice_xings.py:148: RuntimeWarning: invalid value encountered in double_scalars
  std = np.ma.sqrt(np.ma.sum(weight1*weight2*(val-mean)**2) / np.ma.sum(weight1*weight2) )
/work/ALT/odatis/seaice/users/laforga/projet_cryo2ice/code/sortnsave_cryo2ice_xings.py:1804: UserWarning: Warning: converting a masked element to nan.
  array = ma.masked_invalid(np.array(is2_data[gdr][p]))
Traceback (most recent call last):
  File "check_siralb_cryo2ice.py", line 340, in <module>
    corrections_cs2 = earth + lpe + dac + ocean + load # + pole
  File "/softs/rh7/Python/3.7.2/lib/python3.7/site-packages/numpy-1.16.1-py3.7-linux-x86_64.egg/numpy/ma/core.py", line 4067, in __add__
    return add(self, other)
  File "/softs/rh7/Python/3.7.2/lib/python3.7/site-packages/numpy-1.16.1-py3.7-linux-x86_64.egg/numpy/ma/core.py", line 1018, in __call__
    result = self.f(da, db, *args, **kwargs)
ValueError: operands could not be broadcast together with shapes (272697,) (261313,) 
/work/ALT/odatis/seaice/users/laforga/projet_cryo2ice/code/common_functions.py:257: RuntimeWarning: invalid value encountered in arccos
  dist = earthradius_fct_of_lat(latDeg1)*np.arccos( np.sin(deg_to_rad(latDeg1))*np.sin(deg_to_rad(latDeg2)) + np.cos(deg_to_rad(latDeg1))*np.cos(deg_to_rad(latDeg2))*np.cos(deg_to_rad(lonDeg2 - lonDeg1)) )
/work/ALT/odatis/seaice/users/laforga/projet_cryo2ice/code/sortnsave_cryo2ice_xings.py:148: RuntimeWarning: invalid value encountered in double_scalars
  std = np.ma.sqrt(np.ma.sum(weight1*weight2*(val-mean)**2) / np.ma.sum(weight1*weight2) )
/work/ALT/odatis/seaice/users/laforga/projet_cryo2ice/code/sortnsave_cryo2ice_xings.py:1804: UserWarning: Warning: converting a masked element to nan.
  array = ma.masked_invalid(np.array(is2_data[gdr][p]))
Traceback (most recent call last):
  File "check_siralb_cryo2ice.py", line 396, in <module>
    f1.suptitle('Delta sla (la-ku) %s' %(mid_month), fontsize=12)
NameError: name 'month' is not defined
