load python/3.7.2  : OK 
load ct_tools/2.18  : OK 
unload python/3.7.2  : OK 
load python/3.7.2  : OK 
unload ct_tools/2.18  : OK 
load ct_tools/2.18  : OK 
/work/ALT/odatis/seaice/users/laforga/projet_cryo2ice/code/common_functions.py:257: RuntimeWarning: invalid value encountered in arccos
  dist = earthradius_fct_of_lat(latDeg1)*np.arccos( np.sin(deg_to_rad(latDeg1))*np.sin(deg_to_rad(latDeg2)) + np.cos(deg_to_rad(latDeg1))*np.cos(deg_to_rad(latDeg2))*np.cos(deg_to_rad(lonDeg2 - lonDeg1)) )
/work/ALT/odatis/seaice/users/laforga/projet_cryo2ice/code/common_functions.py:257: RuntimeWarning: invalid value encountered in arccos
  dist = earthradius_fct_of_lat(latDeg1)*np.arccos( np.sin(deg_to_rad(latDeg1))*np.sin(deg_to_rad(latDeg2)) + np.cos(deg_to_rad(latDeg1))*np.cos(deg_to_rad(latDeg2))*np.cos(deg_to_rad(lonDeg2 - lonDeg1)) )
/work/ALT/odatis/seaice/users/laforga/projet_cryo2ice/code/common_functions.py:257: RuntimeWarning: invalid value encountered in arccos
  dist = earthradius_fct_of_lat(latDeg1)*np.arccos( np.sin(deg_to_rad(latDeg1))*np.sin(deg_to_rad(latDeg2)) + np.cos(deg_to_rad(latDeg1))*np.cos(deg_to_rad(latDeg2))*np.cos(deg_to_rad(lonDeg2 - lonDeg1)) )
/work/ALT/odatis/seaice/users/laforga/projet_cryo2ice/code/common_functions.py:257: RuntimeWarning: invalid value encountered in arccos
  dist = earthradius_fct_of_lat(latDeg1)*np.arccos( np.sin(deg_to_rad(latDeg1))*np.sin(deg_to_rad(latDeg2)) + np.cos(deg_to_rad(latDeg1))*np.cos(deg_to_rad(latDeg2))*np.cos(deg_to_rad(lonDeg2 - lonDeg1)) )
/work/ALT/odatis/seaice/users/laforga/projet_cryo2ice/code/common_functions.py:257: RuntimeWarning: invalid value encountered in arccos
  dist = earthradius_fct_of_lat(latDeg1)*np.arccos( np.sin(deg_to_rad(latDeg1))*np.sin(deg_to_rad(latDeg2)) + np.cos(deg_to_rad(latDeg1))*np.cos(deg_to_rad(latDeg2))*np.cos(deg_to_rad(lonDeg2 - lonDeg1)) )
/work/ALT/odatis/seaice/users/laforga/projet_cryo2ice/code/common_functions.py:257: RuntimeWarning: invalid value encountered in arccos
  dist = earthradius_fct_of_lat(latDeg1)*np.arccos( np.sin(deg_to_rad(latDeg1))*np.sin(deg_to_rad(latDeg2)) + np.cos(deg_to_rad(latDeg1))*np.cos(deg_to_rad(latDeg2))*np.cos(deg_to_rad(lonDeg2 - lonDeg1)) )
Traceback (most recent call last):
  File "grid_data.py", line 481, in <module>
    beamName = get_strong_beams(filename,is2Beams)
  File "grid_data.py", line 317, in get_strong_beams
    f=h5py.File(filename,'r')
  File "/softs/rh7/Python/3.7.2/lib/python3.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/softs/rh7/Python/3.7.2/lib/python3.7/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 125829120, sblock->base_addr = 0, stored_eof = 344064658)

/work/ALT/odatis/seaice/users/laforga/data/IS2/ATL10/202104/*.h5: No found
